export const affirmationLibrary = [
  "I can move through this moment with steadiness and care.",
  "Healing is not linear, and my effort still counts.",
  "I am allowed to slow down and reconnect with myself.",
  "My emotions carry information, not failure.",
  "I can practice one helpful step at a time.",
  "Safety, structure, and compassion can exist together.",
  "I can return my attention to the present moment.",
  "My breath can be an anchor when life feels uncertain.",
  "I can notice what I feel without becoming overwhelmed by it.",
  "I am here, I am breathing, and I can take the next small step.",
  "I can make room for calm without forcing myself to feel differently.",
  "This moment is temporary, and I can meet it with care.",
  "I can pause before deciding what I need next.",
  "I do not have to solve everything at once.",
  "Rest is a meaningful part of my well-being.",
  "My needs deserve attention and respect.",
  "I can speak to myself with patience.",
  "I am worthy of the same compassion I offer others.",
  "I can learn without criticizing myself for not knowing sooner.",
  "My value is not measured by my productivity.",
  "I am allowed to be a work in progress.",
  "I can acknowledge my strengths without minimizing them.",
  "I deserve care even on difficult days.",
  "I can honor my limits without shame.",
  "I can set a boundary and still be a caring person.",
  "No is a complete and respectful answer when it protects my well-being.",
  "I am responsible for my choices, not for controlling every response.",
  "I can choose relationships that respect my voice and dignity.",
  "My time and energy are valuable.",
  "I can communicate my needs clearly and calmly.",
  "I am allowed to reconsider commitments that harm my well-being.",
  "Healthy boundaries create room for honest connection.",
  "My past experiences do not determine every future possibility.",
  "I can build safety gradually and at my own pace.",
  "My survival responses helped me endure, and I can learn new responses now.",
  "I can be gentle with the parts of me that learned to stay guarded.",
  "I am more than what happened to me.",
  "I can recognize a trigger without blaming myself for having one.",
  "I have permission to heal without explaining my timeline.",
  "I can practice trust in small, thoughtful steps.",
  "Grief reflects the meaning of what I have loved and lost.",
  "I can carry love and grief at the same time.",
  "There is no single correct pace for mourning.",
  "I can remember without requiring myself to feel only one emotion.",
  "My grief deserves tenderness rather than judgment.",
  "I am allowed to experience moments of relief or joy while grieving.",
  "I can ask for companionship when grief feels heavy.",
  "I can honor what was while continuing to live in what is.",
  "I can learn from a setback without defining myself by it.",
  "Recovery is strengthened by honesty, support, and repeated choices.",
  "An urge is an experience, not a command.",
  "I can reach for support before a difficult moment becomes a crisis.",
  "I can begin again without erasing the progress I have made.",
  "My wellness is worth protecting today.",
  "I can choose one action that supports the life I want.",
  "I am capable of practicing new coping skills.",
  "My identity is worthy of dignity, safety, and belonging.",
  "I do not have to shrink myself to deserve acceptance.",
  "I can define myself in language that feels true to me.",
  "My differences are part of my humanity, not a deficiency.",
  "I deserve relationships and spaces where I can be authentic.",
  "I can explore who I am with curiosity rather than judgment.",
  "My voice and lived experience matter.",
  "I belong in my own life.",
  "I can listen to understand before I respond.",
  "Conflict can be addressed without abandoning respect.",
  "I can repair harm while still maintaining my dignity.",
  "I can ask for clarity instead of assuming the worst.",
  "I deserve mutual effort in my relationships.",
  "I can express care without neglecting myself.",
  "I can choose connection that supports honesty and growth.",
  "I am allowed to step away from conversations that are unsafe or harmful.",
  "Caring for others does not require forgetting myself.",
  "I can receive help without seeing it as failure.",
  "I can be present without being perfect.",
  "My care has value, and my well-being matters too.",
  "I can make space for my own needs alongside the needs of others.",
  "I am allowed to rest before I am completely exhausted.",
  "I can ask others to share responsibility.",
  "Sustainable care includes care for the caregiver.",
  "Change can feel uncomfortable and still lead toward growth.",
  "I can make decisions using the information I have today.",
  "I am capable of adapting while staying connected to my values.",
  "I can release the expectation that progress must be perfect.",
  "Uncertainty does not erase my ability to choose thoughtfully.",
  "I can take time to recognize what this transition requires.",
  "Each intentional step helps me build confidence.",
  "I can revise my plan without calling myself a failure.",
  "I have survived difficult chapters and can continue writing my story.",
  "Hope can be quiet and still be real.",
  "There are strengths in me that difficult moments cannot erase.",
  "I can notice one possibility even when I cannot see the whole path.",
  "My future can contain experiences I have not imagined yet.",
  "I can recognize progress that once seemed too small to count.",
  "I am building a life shaped by care, meaning, and choice.",
  "Today offers another opportunity to practice what supports me.",
  "My body deserves nourishment, rest, movement, and respect.",
  "I can listen to my body without judging its needs.",
  "My body is not required to meet someone else's standard to deserve care.",
  "I can approach my health with curiosity and compassion.",
  "I am allowed to choose movement that feels supportive and safe.",
  "I can appreciate what my body helps me experience.",
  "My worth is larger than appearance, ability, age, or diagnosis.",
  "I can take up space with dignity.",
  "I can focus on what is within my influence today.",
  "I can break a large task into manageable steps.",
  "I am capable of learning at a pace that works for me.",
  "Asking a question is a sign of engagement, not inadequacy.",
  "I can use structure to support myself without demanding perfection.",
  "I can celebrate completion without dismissing the effort it required.",
  "My concentration may vary, and I can adjust my approach.",
  "I can return to the task with patience when my attention wanders.",
  "I can make choices consistent with my values.",
  "I can be honest with myself and still be compassionate.",
  "I am allowed to want peace, purpose, and connection.",
  "I can recognize what no longer serves me.",
  "My growth does not require anyone else's permission.",
  "I can protect what matters while remaining open to learning.",
  "I can choose courage in a form that feels realistic today.",
  "I am becoming more aware of what helps me thrive.",
] as const;
