export type PsychoeducationResource = {
  id: string;
  title: string;
  topic: string;
  population: string;
  summary: string;
  keyPoints: string[];
  practice: string;
};

export const psychoeducationLibrary: PsychoeducationResource[] = [
  { id: "stress-response", title: "Understanding the Stress Response", topic: "Trauma", population: "All ages", summary: "How fight, flight, freeze, and fawn responses can affect the body and behavior.", keyPoints: ["A stress response is the nervous system attempting protection.", "Body sensations can appear before a person identifies the trigger.", "Grounding and safety cues can help the body return toward regulation."], practice: "Notice one body cue, name the response without judgment, and identify one present-day safety cue." },
  { id: "trauma-triggers", title: "Trauma Triggers and Present-Day Safety", topic: "Trauma", population: "Adults", summary: "Recognizing reminders of past danger while orienting to present-day safety.", keyPoints: ["Triggers may be sensory, emotional, relational, or situational.", "A triggered response does not mean current danger is certain.", "Choice, pacing, and grounding support stabilization."], practice: "Create two columns: what reminds me of the past, and what tells me I am in the present." },
  { id: "window-tolerance", title: "The Window of Tolerance", topic: "Trauma", population: "Teens and adults", summary: "Understanding hyperarousal, shutdown, and the regulated zone.", keyPoints: ["The regulated zone supports thinking and connection.", "Hyperarousal may feel restless, panicked, or angry.", "Hypoarousal may feel numb, disconnected, or slowed."], practice: "Identify one sign of each state and one strategy that helps you move toward regulation." },
  { id: "grounding-anxiety", title: "Grounding Skills for Anxiety", topic: "Anxiety", population: "All ages", summary: "Practical ways to reconnect with the present during acute anxiety.", keyPoints: ["Grounding uses the senses and present facts.", "Slower exhalation may help settle physical activation.", "Different strategies work for different people."], practice: "Try 5-4-3-2-1 sensory grounding and record what helped." },
  { id: "worry-cycle", title: "Understanding the Worry Cycle", topic: "Anxiety", population: "Teens and adults", summary: "How uncertainty, anxious predictions, and avoidance can reinforce worry.", keyPoints: ["Worry often seeks certainty that is not available.", "Avoidance may reduce anxiety briefly while strengthening it later.", "Small planned actions can build tolerance for uncertainty."], practice: "Write the worry, the prediction, the avoided action, and one manageable next step." },
  { id: "panic", title: "Understanding Panic Symptoms", topic: "Anxiety", population: "Teens and adults", summary: "A nonjudgmental explanation of panic sensations and coping responses.", keyPoints: ["Panic symptoms can feel dangerous even when they are time-limited.", "Fighting sensations can sometimes intensify fear.", "Medical concerns should be evaluated appropriately."], practice: "Name three sensations, rate intensity, and practice a provider-approved grounding response." },
  { id: "behavioral-activation", title: "Behavioral Activation Basics", topic: "Depression", population: "Teens and adults", summary: "How meaningful action can support mood before motivation fully returns.", keyPoints: ["Low mood often reduces activity and reinforcement.", "Small scheduled actions can interrupt withdrawal.", "Activities can support pleasure, mastery, or connection."], practice: "Choose one ten-minute activity and record mood before and after." },
  { id: "self-compassion", title: "Self-Compassion and the Inner Critic", topic: "Self-esteem", population: "Teens and adults", summary: "Responding to self-criticism with accountability and care.", keyPoints: ["Self-compassion is not avoiding responsibility.", "Harsh self-talk can increase shame and avoidance.", "A balanced response can support change."], practice: "Rewrite one critical statement as something truthful, accountable, and kind." },
  { id: "emotion-regulation", title: "Naming and Regulating Emotions", topic: "Emotional regulation", population: "All ages", summary: "Using emotion labels, body awareness, and coping choices.", keyPoints: ["Emotions provide information but do not dictate action.", "Precise labels can make feelings easier to understand.", "Regulation includes allowing and responding, not suppressing."], practice: "Name the emotion, body cue, urge, need, and one effective action." },
  { id: "distress-tolerance", title: "Distress Tolerance During Intense Moments", topic: "Emotional regulation", population: "Teens and adults", summary: "Short-term skills for getting through distress without worsening the situation.", keyPoints: ["Crisis-survival skills are temporary supports.", "Pausing creates space between an urge and an action.", "Ongoing problems still need later attention."], practice: "Build a short list of safe sensory, movement, and connection strategies." },
  { id: "grief", title: "Grief Does Not Follow a Straight Line", topic: "Grief and loss", population: "All ages", summary: "Understanding changing grief reactions without imposing a fixed timeline.", keyPoints: ["Grief can affect emotions, thoughts, sleep, identity, and the body.", "Reactions may return around reminders and transitions.", "Continuing bonds and new meaning can coexist with loss."], practice: "Identify one current grief need and one supportive ritual or connection." },
  { id: "boundaries", title: "Healthy Boundaries", topic: "Relationships", population: "Teens and adults", summary: "Understanding limits, needs, consent, and respectful communication.", keyPoints: ["Boundaries describe what you will do to protect a need or limit.", "Another person may dislike a boundary without making it wrong.", "Safety may require support beyond direct communication."], practice: "Complete: I am available for __; I am not available for __; if __ happens, I will __." },
  { id: "communication", title: "Assertive Communication", topic: "Relationships", population: "Teens and adults", summary: "Expressing needs clearly while respecting self and others.", keyPoints: ["Assertiveness differs from aggression and passivity.", "Specific observations reduce blame.", "A request is not a guarantee of agreement."], practice: "Draft: When __ happens, I feel __, I need __, and I am asking __." },
  { id: "repair", title: "Conflict Repair for Couples", topic: "Couples", population: "Couples", summary: "Ways partners can slow escalation, take responsibility, and reconnect.", keyPoints: ["Regulation may need to happen before problem-solving.", "Repair includes impact, responsibility, and changed action.", "Safety and coercion concerns require a different approach."], practice: "Each partner identifies one impact heard, one responsibility, and one specific repair action." },
  { id: "johari", title: "The Johari Window and Self-Awareness", topic: "Insight", population: "Teens, adults, and couples", summary: "Exploring what is known or unknown to self and others.", keyPoints: ["The open area includes what self and others recognize.", "Feedback may illuminate blind spots without defining the whole person.", "Disclosure should remain voluntary and appropriately paced."], practice: "List qualities in the open, hidden, and possible blind areas; identify one safe insight to explore." },
  { id: "journaling", title: "What Journaling Can Do in Therapy", topic: "Insight", population: "Teens and adults", summary: "How journaling can support reflection, pattern recognition, and emotional processing.", keyPoints: ["Journaling can track patterns between situations, thoughts, feelings, and actions.", "Private entries remain private unless deliberately shared.", "Writing can be brief and does not need to be polished."], practice: "Write for five minutes about one recent pattern, then decide whether to keep it private or share it." },
  { id: "adhd", title: "ADHD and Executive Function", topic: "ADHD", population: "Children, teens, and adults", summary: "How attention, working memory, activation, and time awareness affect daily tasks.", keyPoints: ["Executive-function difficulty is not a character flaw.", "External structure can reduce working-memory demands.", "Strategies should fit the person and environment."], practice: "Choose one task and add a visible cue, smaller first step, and realistic start time." },
  { id: "autistic-regulation", title: "Autistic Regulation and Sensory Needs", topic: "Autism", population: "Children, teens, and adults", summary: "A neurodiversity-affirming overview of sensory load, communication, and regulation.", keyPoints: ["Sensory and communication needs differ across individuals.", "Distress may reflect overload rather than defiance.", "Accommodation and recovery time can support participation."], practice: "Identify one sensory drain, one regulating support, and one accommodation to discuss." },
  { id: "parent-co-regulation", title: "Co-Regulation for Children", topic: "Parenting", population: "Parents and caregivers", summary: "How a regulated adult can help a child develop emotional regulation.", keyPoints: ["Connection and safety support learning.", "Behavior may communicate an unmet need or lagging skill.", "Limits can remain calm, clear, and consistent."], practice: "Plan one validating statement, one limit, and one calming action for a predictable difficult moment." },
  { id: "teen-autonomy", title: "Supporting Adolescent Autonomy", topic: "Parenting", population: "Teens and caregivers", summary: "Balancing growing independence with safety, connection, and accountability.", keyPoints: ["Autonomy grows through supported choices and natural consequences.", "Curiosity can preserve communication better than interrogation.", "Safety limits should be clear and developmentally appropriate."], practice: "Identify one choice the teen can own and one safety boundary the caregiver must maintain." },
  { id: "recovery", title: "Triggers, Cravings, and Recovery Supports", topic: "Substance use", population: "Teens and adults", summary: "Recognizing patterns around substance use and strengthening recovery choices.", keyPoints: ["Cravings can rise and fall without requiring action.", "People, places, emotions, and body states can become triggers.", "Recovery plans benefit from multiple layers of support."], practice: "Map one trigger, warning sign, coping response, and person or service to contact." },
  { id: "harm-reduction", title: "Understanding Harm Reduction", topic: "Substance use", population: "Adults", summary: "A person-centered approach to reducing risk while supporting change.", keyPoints: ["Harm reduction meets people where they are.", "Reducing risk and pursuing recovery are not mutually exclusive.", "Urgent medical risks require appropriate emergency care."], practice: "Identify one realistic risk-reduction step and one longer-term goal to discuss with your provider." },
  { id: "sleep", title: "Sleep and Mental Health", topic: "Wellness", population: "Teens and adults", summary: "How routines, arousal, environment, and health factors interact with sleep.", keyPoints: ["Sleep and emotional health influence each other.", "Consistent wake time can support the body clock.", "Persistent sleep problems may need medical evaluation."], practice: "Track bedtime, wake time, awakenings, and one daytime factor for one week." },
  { id: "older-adult", title: "Emotional Wellness in Later Life", topic: "Older adults", population: "Older adults", summary: "Supporting identity, connection, adjustment, and meaning through later-life changes.", keyPoints: ["Later life can include both losses and continued growth.", "Isolation, grief, health changes, and caregiving can affect mood.", "New confusion or rapid change warrants medical attention."], practice: "Identify one meaningful role, one connection, and one accessible activity to strengthen." },
  { id: "caregiver", title: "Caregiver Stress and Sustainable Support", topic: "Caregiving", population: "Caregivers", summary: "Recognizing caregiver strain and building realistic support.", keyPoints: ["Caregiver stress can affect sleep, mood, health, and relationships.", "Respite and boundaries are parts of care, not failures of care.", "Support plans should include emergencies and backup help."], practice: "List one task to share, one boundary, and one source of respite or practical support." },
  { id: "military-transition", title: "Military-to-Civilian Transition", topic: "Military and veterans", population: "Service members, veterans, and families", summary: "Understanding identity, structure, relationships, and adjustment during transition.", keyPoints: ["Transition can affect purpose, belonging, routine, and family roles.", "Strengths developed in service may need new contexts.", "Peer and culturally responsive supports can reduce isolation."], practice: "Identify one service-based strength and one civilian setting where it can be applied." },
  { id: "identity-affirming", title: "Identity-Affirming Emotional Wellness", topic: "LGBTQ+", population: "Teens and adults", summary: "Separating identity from stigma while strengthening safety, belonging, and self-definition.", keyPoints: ["Identity is not a disorder.", "Minority stress can affect emotional and physical health.", "Affirming relationships and chosen community can be protective."], practice: "Identify one affirming person, place, practice, or statement that supports authenticity and safety." },
  { id: "body-image", title: "Body Image and Body Respect", topic: "Body image", population: "Teens and adults", summary: "Moving from appearance-based judgment toward function, care, and respect.", keyPoints: ["Body image is shaped by personal, relational, cultural, and media messages.", "Body respect does not require constant body positivity.", "Eating or body concerns may require specialized assessment."], practice: "Name one body function you value and one appearance-focused message you want to challenge." },
  { id: "mindfulness", title: "Mindfulness Without Judgment", topic: "Mindfulness", population: "All ages", summary: "Practicing present-moment awareness without demanding a blank mind.", keyPoints: ["Mindfulness is noticing and returning, not eliminating thoughts.", "Short practices count.", "Eyes-open or movement-based practice may feel safer for some people."], practice: "For one minute, notice breath, sound, or movement and gently label each distraction." },
  { id: "cognitive-cycle", title: "Thoughts, Feelings, and Actions", topic: "CBT skills", population: "Children, teens, and adults", summary: "Understanding how interpretations, emotions, physical responses, and behavior interact.", keyPoints: ["Thoughts are meaningful but are not always facts.", "Changing one part of the cycle may influence the others.", "Balanced thinking includes evidence and context."], practice: "Record one situation, thought, feeling, action, and a more balanced alternative thought." },
];
