export const specialtyAssessments = [
  { key: 'cognitiveReview', label: 'Memory Loss / Cognitive Change — Clinical Assessment', group: 'Older adults & caregivers', version: 'Clinical interview' },
  { key: 'geriatricReview', label: 'Geriatric Wellbeing / Function — Clinical Assessment', group: 'Older adults & caregivers', version: 'Clinical interview' },
  { key: 'ad8', label: 'AD8 Dementia Screening Interview', group: 'Older adults & caregivers', version: '' },
  { key: 'iqcode', label: 'Informant Questionnaire on Cognitive Decline in the Elderly (IQCODE)', group: 'Older adults & caregivers', version: '' },
  { key: 'faq', label: 'Functional Activities Questionnaire (FAQ)', group: 'Older adults & caregivers', version: '' },
  { key: 'lawtonIadl', label: 'Lawton Instrumental Activities of Daily Living (IADL)', group: 'Older adults & caregivers', version: '' },
  { key: 'katzAdl', label: 'Katz Index of Independence in Activities of Daily Living', group: 'Older adults & caregivers', version: '' },
  { key: 'identitySupportReview', label: 'LGBTQ+ Identity & Affirming Support — Clinical Assessment', group: 'Identity & affirming support', version: 'Affirming clinical interview' },
  { key: 'genderDistressReview', label: 'Gender-Related Distress / Dysphoria — Clinical Assessment', group: 'Identity & affirming support', version: 'Affirming clinical interview' },
  { key: 'militaryReview', label: 'Military / Veteran / Reintegration — Clinical Assessment', group: 'Military & veterans', version: 'Clinical interview' },
  { key: 'traumaReview', label: 'Trauma and Stress — Clinical Assessment', group: 'Trauma & stress', version: 'Clinical interview' },
  { key: 'pcptsd5', label: 'Primary Care PTSD Screen for DSM-5 (PC-PTSD-5)', group: 'Military & veterans', version: '' },
  { key: 'lec5', label: 'Life Events Checklist for DSM-5 (LEC-5)', group: 'Trauma & stress', version: '' },
  { key: 'drri2', label: 'Deployment Risk and Resilience Inventory–2 (DRRI-2)', group: 'Military & veterans', version: '' },
  { key: 'mies', label: 'Moral Injury Events Scale (MIES)', group: 'Military & veterans', version: '' },
  { key: 'nsi', label: 'Neurobehavioral Symptom Inventory (NSI)', group: 'Military & veterans', version: '' },
  { key: 'caps5', label: 'Clinician-Administered PTSD Scale for DSM-5 (CAPS-5)', group: 'Trauma & stress', version: '' },
  { key: 'itq', label: 'International Trauma Questionnaire (ITQ)', group: 'Trauma & stress', version: '' },
  { key: 'cpSS5', label: 'Child PTSD Symptom Scale for DSM-5 (CPSS-5)', group: 'Trauma & stress', version: '' },
  { key: 'learningReview', label: 'Learning / Reading / Writing / Math — Clinical Assessment', group: 'Learning & school', version: 'Clinical interview' },
  { key: 'autismReview', label: 'Autism / Developmental Profile — Clinical Assessment', group: 'Development & autism', version: 'Clinical interview' },
  { key: 'abaReview', label: 'ABA / Functional Behavior — Clinical Assessment', group: 'ABA & behavior', version: 'Clinical interview and observation' },
  { key: 'nutritionReview', label: 'Nutrition / Feeding — Clinical Assessment', group: 'Nutrition & feeding', version: 'Clinical interview' },
  { key: 'srs2', label: 'Social Responsiveness Scale, Second Edition (SRS-2)', group: 'Development & autism', version: '' },
  { key: 'scq', label: 'Social Communication Questionnaire (SCQ)', group: 'Development & autism', version: '' },
  { key: 'cars2', label: 'Childhood Autism Rating Scale, Second Edition (CARS-2)', group: 'Development & autism', version: '' },
  { key: 'ados2', label: 'Autism Diagnostic Observation Schedule, Second Edition (ADOS-2)', group: 'Development & autism', version: '' },
  { key: 'adir', label: 'Autism Diagnostic Interview–Revised (ADI-R)', group: 'Development & autism', version: '' },
  { key: 'vineland3', label: 'Vineland Adaptive Behavior Scales, Third Edition', group: 'Development & autism', version: '' },
  { key: 'abas3', label: 'Adaptive Behavior Assessment System, Third Edition (ABAS-3)', group: 'Development & autism', version: '' },
  { key: 'sensoryProfile2', label: 'Sensory Profile 2', group: 'Development & autism', version: '' },
  { key: 'wiat4', label: 'Wechsler Individual Achievement Test, Fourth Edition (WIAT-4)', group: 'Learning & school', version: '' },
  { key: 'ktea3', label: 'Kaufman Test of Educational Achievement, Third Edition (KTEA-3)', group: 'Learning & school', version: '' },
  { key: 'ctopp2', label: 'Comprehensive Test of Phonological Processing, Second Edition (CTOPP-2)', group: 'Learning & school', version: '' },
  { key: 'towre2', label: 'Test of Word Reading Efficiency, Second Edition (TOWRE-2)', group: 'Learning & school', version: '' },
  { key: 'brief2', label: 'Behavior Rating Inventory of Executive Function, Second Edition (BRIEF2)', group: 'Learning & school', version: '' },
  { key: 'basc3', label: 'Behavior Assessment System for Children, Third Edition (BASC-3)', group: 'Child & adolescent', version: '' },
  { key: 'conners4', label: 'Conners 4', group: 'Child & adolescent', version: '' },
  { key: 'vbmapp', label: 'VB-MAPP', group: 'ABA & behavior', version: '' },
  { key: 'abllsr', label: 'Assessment of Basic Language and Learning Skills–Revised (ABLLS-R)', group: 'ABA & behavior', version: '' },
  { key: 'mnasf', label: 'Mini Nutritional Assessment–Short Form (MNA-SF)', group: 'Nutrition & feeding', version: '' },
  { key: 'must', label: 'Malnutrition Universal Screening Tool (MUST)', group: 'Nutrition & feeding', version: '' },
  { key: 'nias', label: 'Nine Item ARFID Screen (NIAS)', group: 'Nutrition & feeding', version: '' },
  { key: 'ipos', label: 'Integrated Palliative care Outcome Scale (IPOS)', group: 'Palliative care', version: '' },
  { key: 'bodyImageReview', label: 'Body Image / Dysmorphic Concerns — Clinical Assessment', group: 'Eating & body image', version: 'Clinical interview' },
  { key: 'eatingReview', label: 'Eating Concerns / Bulimia / Binge Eating — Clinical Assessment', group: 'Eating & body image', version: 'Clinical interview' },
  { key: 'bddq', label: 'Body Dysmorphic Disorder Questionnaire (BDDQ)', group: 'Eating & body image', version: '' },
  { key: 'edeq', label: 'Eating Disorder Examination Questionnaire (EDE-Q)', group: 'Eating & body image', version: '' },
  { key: 'sexualHealthReview', label: 'Sexual Health and Function — Clinical Assessment', group: 'Sexual health', version: 'Clinical interview' },
  { key: 'asex', label: 'Arizona Sexual Experiences Scale (ASEX)', group: 'Sexual health', version: '' },
  { key: 'fsfi', label: 'Female Sexual Function Index (FSFI)', group: 'Sexual health', version: '' },
  { key: 'iief', label: 'International Index of Erectile Function (IIEF)', group: 'Sexual health', version: '' },
  { key: 'familyReview', label: 'Family Dynamics — Clinical Assessment', group: 'Families', version: 'Clinical interview' },
  { key: 'familyApgar', label: 'Family APGAR', group: 'Families', version: '' },
  { key: 'fad', label: 'McMaster Family Assessment Device (FAD)', group: 'Families', version: '' },
  { key: 'couplesReview', label: 'Couples / Relationship — Clinical Assessment', group: 'Couples & relationships', version: 'Clinical interview' },
  { key: 'csi', label: 'Couples Satisfaction Index (CSI)', group: 'Couples & relationships', version: '' },
  { key: 'rdas', label: 'Revised Dyadic Adjustment Scale (RDAS)', group: 'Couples & relationships', version: '' },
  { key: 'perinatalReview', label: 'Perinatal / Postpartum — Clinical Assessment', group: 'Pregnancy & postpartum', version: 'Clinical interview' },
  { key: 'epds', label: 'Edinburgh Postnatal Depression Scale (EPDS)', group: 'Pregnancy & postpartum', version: '' },
  { key: 'pass', label: 'Perinatal Anxiety Screening Scale (PASS)', group: 'Pregnancy & postpartum', version: '' },
  { key: 'cooccurringReview', label: 'Dual Diagnosis / Co-occurring Disorders — Clinical Assessment', group: 'Co-occurring disorders', version: 'Clinical interview' },
  { key: 'assist', label: 'WHO ASSIST', group: 'Co-occurring disorders', version: '' },
  { key: 'mhsf3', label: 'Mental Health Screening Form III (MHSF-III)', group: 'Co-occurring disorders', version: '' },
  { key: 'vanderbilt', label: 'Vanderbilt ADHD Rating Scales', group: 'Child & adolescent', version: '' },
  { key: 'mchat', label: 'M-CHAT-R/F', group: 'Development & autism', version: '' },
  { key: 'aq10', label: 'Autism Spectrum Quotient (AQ-10)', group: 'Development & autism', version: '' },
  { key: 'gds', label: 'Geriatric Depression Scale (GDS)', group: 'Older adults & caregivers', version: '' },
  { key: 'zarit', label: 'Zarit Burden Interview', group: 'Older adults & caregivers', version: '' },
  { key: 'mdq', label: 'Mood Disorder Questionnaire (MDQ)', group: 'Mood & anxiety', version: '' },
  { key: 'ocir', label: 'Obsessive-Compulsive Inventory–Revised (OCI-R)', group: 'Mood & anxiety', version: '' },
  { key: 'isi', label: 'Insomnia Severity Index (ISI)', group: 'Sleep', version: '' },
  { key: 'pg13r', label: 'Prolonged Grief Disorder–13–Revised (PG-13-R)', group: 'Grief', version: '' },
  { key: 'whodas', label: 'WHODAS 2.0', group: 'Functioning & disability', version: '' },
  { key: 'mse', label: 'Mental Status Exam (MSE)', group: 'Mental health', version: 'Clinical MSE' },
  { key: 'audit', label: 'AUDIT', group: 'Addiction & substance use', version: 'AUDIT — 10 items' },
  { key: 'cageAid', label: 'CAGE-AID', group: 'Addiction & substance use', version: 'CAGE-AID — 4 items' },
  { key: 'psc', label: 'Pediatric Symptom Checklist (PSC)', group: 'Child & adolescent', version: '' },
  { key: 'scared', label: 'SCARED', group: 'Child & adolescent', version: '' },
  { key: 'asq', label: 'Ages & Stages Questionnaires (ASQ)', group: 'Child & adolescent', version: '' },
  { key: 'mmse', label: 'Mini-Mental State Examination (MMSE)', group: 'Cognition & attention', version: '' },
  { key: 'moca', label: 'Montreal Cognitive Assessment (MoCA)', group: 'Cognition & attention', version: '' },
  { key: 'asrs', label: 'Adult ADHD Self-Report Scale (ASRS)', group: 'Cognition & attention', version: '' },
  { key: 'pcl5', label: 'PCL-5', group: 'Trauma & stress', version: 'PCL-5' },
  { key: 'tec', label: 'Trauma Experiences Checklist (TEC)', group: 'Trauma & stress', version: '' },
  { key: 'scoff', label: 'SCOFF', group: 'Eating & body image', version: 'SCOFF — 5 items' },
  { key: 'eat26', label: 'Eating Attitudes Test (EAT-26)', group: 'Eating & body image', version: 'EAT-26' },
  { key: 'otherInstrument', label: 'Other named assessment — record results', group: 'Additional assessments', version: '' },
] as const;
export const mseDomains = [
  'Appearance and grooming', 'Behavior and engagement', 'Psychomotor activity',
  'Speech', 'Mood (client report)', 'Affect (observed)', 'Thought process',
  'Thought content', 'Perception', 'Orientation', 'Attention and concentration',
  'Memory', 'Insight', 'Judgment', 'Safety: suicidal and homicidal thoughts',
] as const;
export const clinicalDomains: Record<string, readonly string[]> = {
  mse: mseDomains,
  cognitiveReview: ['Client and informant concerns, consent and information sources', 'Onset, progression, fluctuation and change from baseline', 'Memory, attention, language and executive-function concerns', 'Orientation and observed cognition', 'Daily functioning, medication management and finances', 'Mood, sleep, substance use and sensory limitations', 'Medical history, recent illness, head injury and medications', 'Safety, falls, getting lost, driving and vulnerability concerns', 'Caregiver observations, supports and burden', 'Medical, neuropsychological or memory-clinic referral needs'],
  geriatricReview: ['Client priorities, strengths and living situation', 'Mood, cognition, social connection and grief', 'Basic and instrumental daily activities', 'Mobility, falls and assistive devices', 'Hearing, vision, communication and accessibility', 'Nutrition, hydration and feeding concerns', 'Medical conditions, pain, sleep and medications', 'Caregiver support and strain', 'Safety, neglect, exploitation and protective supports', 'Care coordination, goals and referral needs'],
  identitySupportReview: ['Client’s goals and consent to discuss identity', 'Name, pronouns and terms the client wants used', 'Gender identity in the client’s own words, if shared', 'Sexual orientation in the client’s own words, if shared', 'Body-related experiences, comfort or distress, if relevant', 'Affirming relationships, community and strengths', 'Discrimination, rejection, bullying or minority stress', 'Safety, belonging and access to support', 'Privacy, disclosure and communication preferences', 'Requested resources, support or referrals'],
  genderDistressReview: ['Client’s concerns and preferred language', 'Gender-related experiences and client-defined goals', 'Nature, onset and duration of distress, if present', 'Body-related and social experiences of comfort or distress', 'Impact on daily functioning and relationships', 'Developmental context and supports', 'Co-occurring concerns and other contributors to distress', 'Safety, discrimination and protective factors', 'Privacy and disclosure preferences', 'Requested affirming support or further evaluation'],
  militaryReview: ['Service or military-family context and client preferences', 'Presenting concerns and strengths', 'Service-related stress and exposures the client chooses to discuss', 'Trauma symptoms, onset, duration and functional impact', 'Transition, reintegration, family and employment context', 'Loss, grief, guilt, shame or moral injury concerns', 'Sleep, pain, injury and possible brain-injury history', 'Substance use, medications and medical care', 'Suicide, violence and immediate safety concerns', 'Protective factors, community and veteran supports', 'VA, military or community care coordination and referral needs'],
  traumaReview: ['Client priorities, readiness and consent to discuss trauma', 'Relevant exposures and history at a tolerable level of detail', 'Intrusions, avoidance, mood and arousal concerns', 'Dissociation and disturbances in self-organization', 'Onset, duration, triggers and functional impact', 'Developmental, cultural and relational context', 'Sleep, substance use and medical contributors', 'Current safety and ongoing exposure', 'Strengths, stabilization needs and supports'],
  learningReview: ['Age, grade, language and educational context', 'Child and caregiver concerns and strengths', 'Developmental, medical, hearing and vision history', 'Reading, decoding and comprehension concerns', 'Written expression, spelling and handwriting concerns', 'Math calculation and reasoning concerns', 'Attention, executive functioning and emotional context', 'Instruction, attendance, interventions and response', 'Teacher reports, prior evaluations and IEP or 504 supports', 'Functional impact and educational evaluation needs'],
  autismReview: ['Age, developmental history and information sources', 'Communication preferences, language and interaction', 'Interests, routines and repetitive behaviors', 'Sensory preferences, sensitivities and regulation', 'Adaptive skills and everyday support needs', 'Strengths, interests and client or caregiver priorities', 'Co-occurring developmental, medical and mental health concerns', 'School, home and community context', 'Prior diagnoses, assessments and historical terminology', 'Safety, accessibility and diagnostic referral needs'],
  abaReview: ['Client goals, assent and caregiver consent as applicable', 'Behavior definition using observable terms', 'Setting, participants and observation dates', 'Antecedents and relevant setting events', 'Observed behavior, frequency, duration and intensity', 'Consequences observed', 'Communication, sensory and unmet needs', 'Medical, pain, sleep and environmental contributors', 'Baseline data and strengths', 'Possible function and supporting or conflicting evidence', 'Safety, least restrictive supports and further assessment needs'],
  nutritionReview: ['Age, developmental stage and information sources', 'Client or caregiver nutrition and feeding concerns', 'Typical food and fluid intake', 'Food access, culture, preferences and allergies', 'Appetite, recent intake changes and growth or weight history', 'Sensory, chewing, swallowing or gastrointestinal concerns', 'Eating disorder concerns and associated distress', 'Medical conditions, medications and supplements', 'Available medical or nutrition records and limitations', 'Medical, feeding specialist or dietitian referral needs'],
  bodyImageReview: ['Client’s description of body-image concerns', 'Onset, duration and time occupied by concerns', 'Checking, comparison, reassurance-seeking and avoidance', 'Distress and impact on daily life', 'Relationship to eating, weight and shape concerns', 'Insight and expectations about appearance changes', 'Medical history and prior treatment', 'Safety, self-harm concerns and supports'],
  eatingReview: ['Client concerns, onset and duration', 'Restriction, food avoidance and nutritional intake', 'Binge episodes and perceived loss of control', 'Compensatory behaviors, frequency and duration', 'Body-image, weight and shape concerns', 'Medical symptoms, dehydration, fainting or other urgent concerns', 'Medication, substance use and relevant medical history', 'Functional impact, supports and safety', 'Medical and nutrition evaluation or referral needs'],
  sexualHealthReview: ['Client concerns, goals and consent to discuss sexual health', 'Onset, duration and situational or persistent pattern', 'Desire and interest', 'Arousal, erection or lubrication concerns as applicable', 'Orgasm or ejaculation concerns as applicable', 'Pain, discomfort or penetration concerns as applicable', 'Distress, functioning and relationship context', 'Medical conditions, medications, hormonal changes and substances', 'Trauma, coercion, consent and current safety when relevant', 'Concerns about loss of control and resulting impairment when relevant', 'Medical evaluation and specialist referral needs'],
  familyReview: ['Participants and relationships', 'Presenting concerns and each participant’s perspective', 'Family structure, caregiving and roles', 'Communication and conflict patterns', 'Boundaries and decision-making', 'Culture, stressors and major transitions', 'Strengths and supports', 'Safety, coercion, abuse and safeguarding', 'Shared and individual goals'],
  couplesReview: ['Participants and relationship context', 'Each partner’s concerns and goals', 'Communication and conflict repair', 'Trust, attachment and emotional connection', 'Intimacy and boundaries', 'Parenting, finances and shared responsibilities', 'Strengths and supports', 'Private safety screening, coercion and suitability for conjoint sessions', 'Consent and confidentiality expectations'],
  perinatalReview: ['Pregnancy or postpartum stage and relevant dates', 'Mood and anxiety symptoms, onset and duration', 'Sleep, appetite and functioning', 'Bonding, caregiving and available support', 'Birth experiences, losses and medical concerns', 'Past mood episodes, mania or psychosis', 'Intrusive thoughts, intent and safety of parent and infant', 'Medication, substance use and care coordination', 'Protective factors and urgent care needs'],
  cooccurringReview: ['Mental health symptoms and functional impact', 'Substances, amount, route, frequency and last use', 'Symptom timeline relative to substance use and abstinence', 'Withdrawal, overdose and urgent medical concerns', 'Past treatment and recovery history', 'Medication and other medical conditions', 'Readiness, strengths and recovery supports', 'Suicide, violence and safeguarding concerns', 'Integrated care and coordination needs'],
};
export function validateSpecialtyAssessment(key: string, data: Record<string, string>) {
  if (!specialtyAssessments.some(item => item.key === key)) return 'Select an assessment.';
  if (!/^\d{4}-\d{2}-\d{2}$/.test(data.administrationDate || '') || !Number.isFinite(Date.parse(data.administrationDate))) return 'Enter the administration date.';
  if (!data.examiner?.trim()) return 'Enter the examiner name.';
  if (!data.referralStatus?.trim()) return 'Document the further evaluation or referral decision.';
  if (data.totalScore?.trim() && !Number.isFinite(Number(data.totalScore))) return 'Enter a numeric total score, or leave it blank when not applicable.';
  if (!['No referral indicated at this time', 'Further evaluation by primary clinician'].includes(data.referralStatus) && (!data.referralDestination?.trim() || !data.referralReason?.trim())) return 'Document the referral destination and reason.';

  if (!data.interpretation?.trim() || !data.followUp?.trim()) return 'Enter the clinical interpretation and follow-up plan.';
  if (clinicalDomains[key]) {
    if (clinicalDomains[key].some(domain => !data[domain]?.trim())) return 'Document each clinical area, or enter “Not assessed” with a reason.';
  } else if (!data.version?.trim() || !data.respondent?.trim() || !data.results?.trim() || !data.source?.trim()) {
    return 'Enter the exact form/version, respondent, results, and source record.';
  }
  return '';
}
